### ISSUE TITLE
more datasets with different persons needed

### ISSUE THREAD

**Issue by SteveSZF** [gafniguy/4D-Facial-Avatars#11]
> https://syncandshare.lrz.de/getlink/fi9dX7xk9kQ8cN7WS4pNkNBU/dave.zip

Hi, could you share other datasets that are shown in your paper? Thank you!

**Comment by Jia-Wei-Liu** [comment]
Hi, 
Thanks for sharing your code and dataset. I have the same question. It seems you only released one person's data. I wonder if you have any plan to release more people's data as used in your paper? Thank you!
Best regards!

**Comment by gafniguy** [comment]
Hey, I've updated a link to a dataset of 3 people in the readme
