### ISSUE TITLE
foy_y to focal length

### ISSUE THREAD

**Issue by xinwen-cs** [gafniguy/4D-Facial-Avatars#12]
Hi, thanks for you for this great job.
I have a question on camera intrinsics.
I implement a face tracker with fixed fov_y(I didn't do camera calibration because I use online video as input), how can I transform fov_y to the focal length in the json file.

Is this formula correct?
fy = image_height / (2 * tan(fov_y / 2))

**Comment by qiliux** [comment]
hi, this formula is the same as the code in load_flame.py,
do you know why `camera_angle_x = float(meta["camera_angle_x"])` is negative?
