### ISSUE TITLE
Training time

### ISSUE THREAD

**Issue by Tara8573** [gafniguy/4D-Facial-Avatars#13]
Wonderful Work! I have a question about training time. Could you tell me what is the average training time for this model to get relatively good results？

**Comment by Tara8573** [comment]
Thank you so much! And I have another question, how to calculate the value of **near** and **far**   [](https://github.com/gafniguy/4D-Facial-Avatars/blob/406c81ae7a1427a11b4484329544f976c1dd774e/nerface_code/nerf-pytorch/config/dave/dave_dvp_lcode_fixed_bg_512_paper_model.yml#L39)

**Comment by gafniguy** [comment]
I normalize the data in the jsons such that the face is about 0.5 from the camera in the z dim, so it's pretty much always safe to go with 0.2 and 0.8 for far
