### ISSUE TITLE
eval_transformed_rays.py print out same images.

### ISSUE THREAD

**Issue by StephenCha** [gafniguy/4D-Facial-Avatars#19]
Hello.
Thank you for sharing the great code. 
When I used the evaluation code (eval_transformed_rays.py), there was AN ISSUE—the code printed out the same images. 
![Screen Shot 2022-02-21 at 19 25 38](https://user-images.githubusercontent.com/17807597/154936630-134a1aab-db25-4011-b3c1-fb4b71e8adb1.png)
I trained the person_1 dataset using train_transformed_rays.py code to get checkpoints. Then, I used the 295000 checkpoint file made myself.
Is there anyone who solves this problem or has no errors? 
Thanks.

**Comment by gafniguy** [comment]
Hi, try setting ablate = None in line 420 of the evaluation script

**Comment by StephenCha** [comment]
Thank you for your fast reply. I solve it. I appreciate your help.
