### ISSUE TITLE
About real_to_nerf.py

### ISSUE THREAD

**Issue by StephenCha** [gafniguy/4D-Facial-Avatars#20]
Hello.
Thank you for your excellent work. NerFACE is helpful for my study. 
I recorded my video sequence to make a JSON file. Then, using FFmpeg, I made frame image files. However, I've got this error.

####################################################################################
Reading tracked face data
found 2877 images in image folder
Traceback (most recent call last):
  File "real_to_nerf.py", line 1532, in <module>
    generate_driven_test_sequence(configargs, 1000)
  File "real_to_nerf.py", line 1144, in generate_driven_test_sequence
    intrinsics = read_intrinsics(os.path.join(args.source, "intrinsics.txt"), im_size)
  File "real_to_nerf.py", line 64, in read_intrinsics
    all_intrinsics = np.genfromtxt(path_to_intrinsics_txt, dtype=None)
  File "/home/stephencha/.local/lib/python3.8/site-packages/numpy/lib/npyio.py", line 1813, in genfromtxt
    fid = np.lib._datasource.open(fname, 'rt', encoding=encoding)
  File "/home/stephencha/.local/lib/python3.8/site-packages/numpy/lib/_datasource.py", line 193, in open
    return ds.open(path, mode, encoding=encoding, newline=newline)
  File "/home/stephencha/.local/lib/python3.8/site-packages/numpy/lib/_datasource.py", line 532, in open
    raise FileNotFoundError(f"{path} not found.")
FileNotFoundError: ./real2nerf/source/intrinsics.txt not found.
####################################################################################

**I would like to know how to make an intrinsics.txt file.**
I think I should make intrinsics.txt using frame tracking to go forward. So I searched GitHub, and I found some useful open sources.

https://github.com/kimoktm/Face2face 
https://github.com/YadiraF/DECA

The train JSON file contains camera x, expression, and bounding box parameters. I think DECA (including FLAME) could make these parameters. However, I could not know what was inside the intrinsics.txt file. 

Thanks.

**Comment by gafniguy** [comment]
Hi, 
it's the camera intrinsics, fx fy cx cy
cx and cy are normalized by the image size

**Comment by StephenCha** [comment]
I appreciate your reply. Thank you :)
