### ISSUE TITLE
Could not get the psnr result as paper mentioned

### ISSUE THREAD

**Issue by Rainiver** [gafniguy/4D-Facial-Avatars#27]
Hi, thanks for your great work ! I trained the model and could get visual good result.The frame results are attached below:
![0185](https://user-images.githubusercontent.com/101853717/159839471-240f9b64-22a5-4283-b984-31cb0806fb50.png)
I trained 40k iterations, however,the validation psnr is less than 20, far below of the result about psnr **26.85**. I wonder if it is because of the different dataset. So could you please provide the dataset which can be tested psnr 26.85 in the paper ?

**Comment by gafniguy** [comment]
Hi, 

The numbers are averaged over 3 test subjects. For this one, the PSNR over the test sequence is 21.8949. For the other two actors it's 30.3849 and 28.2824. I guess this one (or his shoulders) occupies more pixels in the image hence lower PSNR for this subject. 

I've published recently the dataset for the other 2 subjects too.

**Comment by Rainiver** [comment]
Thanks for your reply. This really helps me!
