### ISSUE TITLE
How to achieve the same effect of facial replay as the paper, and whether it can achieve real-time?

### ISSUE THREAD

**Issue by Chopin68** [gafniguy/4D-Facial-Avatars#29]
![image](https://user-images.githubusercontent.com/75252160/160592837-65df7ca2-dd08-42e3-bbbd-2127ef08a04a.png)
When I follow the steps to generate the image of this step, what should I do next，Hope to get guidance!

**Comment by gafniguy** [comment]
Line 420 in the eval script is causing the pose and expression to be fixed. Set it to None

**Comment by Chopin68** [comment]
> eval 脚本中的第 420 行导致姿势和表情被固定。将其设置为无

Thank you for your reply!! I reported an error after running the following code

python real_to_nerf.py --source K:/GAN/4D-Facial-Avatars-main/nerface_code/nerf-pytorch/real_data/person_1 --target K:/GAN/4D-Facial-Avatars-main/nerface_code/nerf-pytorch/renders/person_1_rendered_frames

Traceback (most recent call last):
  File "K:\GAN\4D-Facial-Avatars-main\nerface_code\nerf-pytorch\real_to_nerf.py", line 7, in <module>
    proc1 = subprocess.Popen(['scontrol', 'show', 'job', os.environ['SLURM_JOBID'], '-d'], stdout=subprocess.PIPE)
  File "C:\Users\CHOPY\AppData\Local\Programs\Python\Python39\lib\os.py", line 679, in __getitem__
    raise KeyError(key) from None
KeyError: 'SLURM_JOBID'
