### ISSUE TITLE
Is it possible to extract meshes from the learned volume?

### ISSUE THREAD

**Issue by sunshineatnoon** [gafniguy/4D-Facial-Avatars#33]
Hi, I was wondering if we can extract meshes from the learned NeRFs as in the [original NeRF repo](https://github.com/yenchenlin/nerf-pytorch/blob/dev/extract_mesh.ipynb). Specifically, how to sample a valid cube? What's the range of the coordinates should be? Thanks!

**Comment by gafniguy** [comment]
Hi, I think it should be possible, I haven't tried it though. 

The whole scene is bounded in the unit cube, scene is normalized such that the face is at an average of z=0.5 from the camera. 


A different way to get a mesh that should be ok for faces, without having to samples a grid and do MC, as faces are very simple surfaces, is to render an expected depth map (use more ray samples though), unproject it to a point cloud and run poison reconstruction. 

![image](https://user-images.githubusercontent.com/37619828/167605555-e6631fa8-c5d0-4318-9f4a-3cc106b15045.png)

**Comment by sunshineatnoon** [comment]
> Hi, I think it should be possible, I haven't tried it though.
> 
> The whole scene is bounded in the unit cube, scene is normalized such that the face is at an average of z=0.5 from the camera.
> 
> A different way to get a mesh that should be ok for faces, without having to samples a grid and do MC, as faces are very simple surfaces, is to render an expected depth map (use more ray samples though), unproject it to a point cloud and run poison reconstruction.
> 
> ![image](https://user-images.githubusercontent.com/37619828/167605555-e6631fa8-c5d0-4318-9f4a-3cc106b15045.png)

Thanks so much for your response. Could you point me to which code you use to extract the mesh? Thanks!
