### ISSUE TITLE
index out of bounds

### ISSUE THREAD

**Issue by JZArray** [gafniguy/4D-Facial-Avatars#44]
After successfully training, there is an error during evaluation:

File "eval_transformed_rays.py", line 433, in main
    _, ray_directions_ablation = get_ray_bundle(hwf[0], hwf[1], hwf[2], render_poses[240+i][:3, :4])
IndexError: index 1000 is out of bounds for dimension 0 with size 1000

Do you have the idea how to fix this?

Thanks in advance!

**Comment by gafniguy** [comment]
Remove anything with 'ablation' in it from the code
