### ISSUE TITLE
which repo you used in quantitative evaluation for DVP(Deep Video Portrait)?

### ISSUE THREAD

**Issue by yangqing-yq** [gafniguy/4D-Facial-Avatars#52]
hi, 

I want to know which repo you used in quantitative evaluation for DVP? There is no open source repo in the github. 
Could you share the link of this work (DVP) you used in your paper ?

**Comment by gafniguy** [comment]
DVP's authors were kind enough to run comparisons for me.

Am 29.12.2022 11:50 schrieb "Qing Yang (Charles)" ***@***.***>:

hi,

I want to know which repo you used in quantitative evaluation for DVP? There is no open source repo in the github.
Could you share the link of this work (DVP) you used in your paper ?

**Comment by yangqing-yq** [comment]
got it. thanks for quick reply.
