### ISSUE TITLE
nerf MLP architecture

### ISSUE THREAD

**Issue by zhengyuf** [gafniguy/4D-Facial-Avatars#8]
Hello,

Thank you for your nice work. I noticed that the nerf MLP architecture in your paper is slightly different than the original nerf implementation, i.e. 1 hidden layer for RGB prediction --> 4 hidden layers with halved width.

I wonder whether you've tried the original nerf architecture and whether you changed it because the modified architecture gives better results.

Thank you in advance for your answer:)

Yufeng

**Comment by gafniguy** [comment]
Hi Yufeng,

Thanks! I haven't put much effort into looking into that. In the beginning of the nerf craze there were different descriptions of their [Mildenhall et al.] architecture in the supplementary and the paper versions. Therefore the torch repo I based on was using some version, and I just went with that. 

I think going with the currently official nerf architecture should be a safe choice. For general Info, in his lecture about nerfs, Vladlen Koltun says the fact that there are very few layers that use the view conditioning is actually key to the success of nerf. He argues you don't want to put too many weights there. [https://youtu.be/Rd0nBO6--bM?t=3128](url)

**Comment by zhengyuf** [comment]
Thank you. That solved my issue!
