### ISSUE TITLE
Add details

### ISSUE THREAD

**Issue by flynnamy** [gafniguy/4D-Facial-Avatars#9]
Hi，I found that there are so many configs. Please add some details on in README. @gafniguy

**Comment by yaokxx** [comment]
LOL, I have the same requirement!!!

**Comment by gafniguy** [comment]
Hey will do as soon as I get some time, hopefully over the weekend.

**Comment by quangtn266** [comment]
Hi all and author,

I saw your paper and realized that your model could do reconstruction and change pose and expression, but how can I do that?

Can you explain more details?

**Comment by gafniguy** [comment]
Hey I added some info, let me know if you need more specific info
